bool register_cell_cmd(sta::LibertyCell *cell, bool verbose);
void prepare_cuts_cmd(int cuts, int matches, int max_cut);
void read_aiger_cmd(const char *filename, const char *name);
void portlist_cmd();
void write_aig_verilog(const char *filename, const char *module_name);
void report_mapping();
void extract_mapping();
void mapping_round_cmd(const char *kind, float param, bool param2);
void report_aig();
void lose_choices();
void report_sibling_usage();
void prune_targets_cmd();
